name: Deploy Widget with Secrets
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create config.js
        run: |
          echo "const config = { accessToken: '${{ secrets.ACCESSTOKEN }}' };" > config.js
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets. }}
          publish_dir: .
